version: "3.7"
services:
  test_db:
    image: postgres:15.1-alpine
    container_name: test_db
    command: postgres -p 5322
    expose:
      - 5322
    env_file:
      - .env
    restart: always

  all_tests:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: all_tests
    ports:
      - "1666:8000"
    command: ["pytest", "./app/tests/unit_tests/test_menus.py"]
    depends_on:
      - test_db
