"""up

Revision ID: 19196ee796bc
Revises: 42db79e2e727
Create Date: 2024-01-20 21:35:23.757779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19196ee796bc'
down_revision: Union[str, None] = '42db79e2e727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.drop_column('menu', 'dishes_count')
    op.drop_column('menu', 'submenus_count')
    op.drop_column('submenu', 'dishes_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenu', sa.Column('dishes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('menu', sa.Column('submenus_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('menu', sa.Column('dishes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('dish', 'price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
